import base64

import pytest
import sqlalchemy as sa

from factory_orchestrator.config import Secret, load_config
from factory_orchestrator.console_secrets import (
    ConsoleSecretStore,
    SealedSecretError,
    apply_console_secrets,
    apply_runtime_agent_secrets,
    decrypt_sealed,
    refresh_console_secrets,
    seal,
)

from .test_config import BASE

MASTER_KEY = "EjRWeJq83vASNFZ4mrze8BI0VniavN7wEjRWeJq83vA="  # fixed 32-byte test key

# Generated by the Console's actual crypto.ts (node createCipheriv aes-256-gcm)
# with MASTER_KEY and a fixed IV — the cross-language compatibility pin.
CONSOLE_SEALED = "v1.AAECAwQFBgcICQoL.ityHH0Dw5EgeHrnEkYhOxA==.icmtZdTo6iYRjab+Qafn0l7jkoQ7aQ=="
CONSOLE_PLAINTEXT = "sk-ant-retained-secret"


def test_decrypts_console_sealed_secret():
    assert decrypt_sealed(CONSOLE_SEALED, MASTER_KEY) == CONSOLE_PLAINTEXT


def test_seal_roundtrip_matches_format():
    sealed = seal("hello world", MASTER_KEY)
    assert sealed.startswith("v1.") and len(sealed.split(".")) == 4
    assert decrypt_sealed(sealed, MASTER_KEY) == "hello world"


@pytest.mark.parametrize("bad", [
    "v2.a.b.c", "v1.only.two", "not-sealed", "v1...",
])
def test_malformed_sealed_rejected(bad):
    with pytest.raises(SealedSecretError, match="malformed"):
        decrypt_sealed(bad, MASTER_KEY)


def test_wrong_key_rejected():
    other = base64.b64encode(b"\x01" * 32).decode()
    with pytest.raises(SealedSecretError, match="decrypt"):
        decrypt_sealed(CONSOLE_SEALED, other)


def test_short_master_key_rejected():
    with pytest.raises(SealedSecretError, match="32 bytes"):
        decrypt_sealed(CONSOLE_SEALED, base64.b64encode(b"short").decode())


# ---------------------------------------------------------------- store
def make_console_db(tmp_path, rows):
    url = f"sqlite:///{tmp_path}/console.db"
    engine = sa.create_engine(url, future=True)
    with engine.begin() as cx:
        cx.execute(sa.text(
            "CREATE TABLE IF NOT EXISTS orchestrator_secrets "
            "(id TEXT PRIMARY KEY, org_id TEXT, name TEXT, encrypted_value TEXT, "
            "updated_by TEXT, updated_at TEXT)"))
        for i, (org, name, value) in enumerate(rows):
            cx.execute(sa.text(
                "INSERT INTO orchestrator_secrets (id, org_id, name, encrypted_value) "
                "VALUES (:id, :org, :name, :sealed)"),
                {"id": str(i), "org": org, "name": name, "sealed": seal(value, MASTER_KEY)})
    return url


def test_store_reads_and_decrypts_single_org(tmp_path):
    url = make_console_db(tmp_path, [
        ("org-1", "ANTHROPIC_API_KEY", "sk-ant-from-console"),
        ("org-1", "FACTORY_CROSS_REPO_TOKEN", "ghp_cross"),
        ("org-1", "NOT_AN_AGENT_SECRET", "ignored"),
    ])
    store = ConsoleSecretStore(url, MASTER_KEY)
    assert store.agent_secrets() == {"ANTHROPIC_API_KEY": "sk-ant-from-console",
                                     "FACTORY_CROSS_REPO_TOKEN": "ghp_cross"}


def test_store_requires_org_choice_when_ambiguous(tmp_path):
    url = make_console_db(tmp_path, [
        ("org-1", "ANTHROPIC_API_KEY", "a"),
        ("org-2", "ANTHROPIC_API_KEY", "b"),
    ])
    with pytest.raises(SealedSecretError, match="CONSOLE_ORG"):
        ConsoleSecretStore(url, MASTER_KEY).agent_secrets()
    assert ConsoleSecretStore(url, MASTER_KEY, org="org-2").agent_secrets() == {
        "ANTHROPIC_API_KEY": "b"}


def test_store_ttl_and_invalidate(tmp_path):
    url = make_console_db(tmp_path, [("org-1", "ANTHROPIC_API_KEY", "v1-value")])
    store = ConsoleSecretStore(url, MASTER_KEY, ttl_seconds=3600)
    assert store.agent_secrets()["ANTHROPIC_API_KEY"] == "v1-value"
    engine = sa.create_engine(url, future=True)
    with engine.begin() as cx:
        cx.execute(sa.text("UPDATE orchestrator_secrets SET encrypted_value = :s"),
                   {"s": seal("v2-value", MASTER_KEY)})
    # within TTL: cached
    assert store.agent_secrets()["ANTHROPIC_API_KEY"] == "v1-value"
    store.invalidate()
    assert store.agent_secrets()["ANTHROPIC_API_KEY"] == "v2-value"


def test_placeholder_env_yields_to_console(tmp_path):
    url = make_console_db(tmp_path, [("org-1", "ANTHROPIC_API_KEY", "console-key")])
    store = ConsoleSecretStore(url, MASTER_KEY)
    env = {"ANTHROPIC_API_KEY": "sk-dev-placeholder"}
    merged, from_console = apply_console_secrets(env, store)
    assert merged["ANTHROPIC_API_KEY"] == "console-key"
    assert from_console == {"ANTHROPIC_API_KEY"}


def test_dispatch_applies_oauth_and_clears_placeholder_api_key():
    cfg = load_config({**BASE, "ANTHROPIC_API_KEY": "sk-dev-placeholder"})
    assert not cfg.anthropic_api_key.usable()
    applied = apply_runtime_agent_secrets(cfg, {"claude_code_oauth_token": "oauth-from-console"})
    assert applied == ["CLAUDE_CODE_OAUTH_TOKEN"]
    assert cfg.claude_code_oauth_token.reveal() == "oauth-from-console"
    assert not cfg.anthropic_api_key.usable()


def test_env_wins_console_fills_gaps(tmp_path):
    url = make_console_db(tmp_path, [
        ("org-1", "ANTHROPIC_API_KEY", "console-key"),
        ("org-1", "FACTORY_CROSS_REPO_TOKEN", "console-cross"),
    ])
    store = ConsoleSecretStore(url, MASTER_KEY)
    env = {"ANTHROPIC_API_KEY": "env-key", "FACTORY_CROSS_REPO_TOKEN": ""}
    merged, from_console = apply_console_secrets(env, store)
    assert merged["ANTHROPIC_API_KEY"] == "env-key"          # env wins
    assert merged["FACTORY_CROSS_REPO_TOKEN"] == "console-cross"
    assert from_console == {"FACTORY_CROSS_REPO_TOKEN"}


def test_config_valid_with_console_supplied_credential(tmp_path):
    url = make_console_db(tmp_path, [("org-1", "ANTHROPIC_API_KEY", "console-key")])
    env = {**BASE, "ANTHROPIC_API_KEY": ""}  # deployment sets no Anthropic credential
    merged, from_console = apply_console_secrets(env, ConsoleSecretStore(url, MASTER_KEY))
    cfg = load_config(merged)
    assert cfg.anthropic_api_key.reveal() == "console-key"
    assert from_console == {"ANTHROPIC_API_KEY"}


def test_refresh_updates_only_console_fields(tmp_path):
    url = make_console_db(tmp_path, [("org-1", "ANTHROPIC_API_KEY", "old-key")])
    store = ConsoleSecretStore(url, MASTER_KEY, ttl_seconds=3600)
    env = {**BASE, "ANTHROPIC_API_KEY": "", "CLAUDE_CODE_OAUTH_TOKEN": "env-oauth"}
    merged, from_console = apply_console_secrets(env, store)
    cfg = load_config(merged)
    engine = sa.create_engine(url, future=True)
    with engine.begin() as cx:
        cx.execute(sa.text("UPDATE orchestrator_secrets SET encrypted_value = :s"),
                   {"s": seal("rotated-key", MASTER_KEY)})
    refresh_console_secrets(cfg, store, from_console)
    assert cfg.anthropic_api_key.reveal() == "rotated-key"
    assert cfg.claude_code_oauth_token.reveal() == "env-oauth"  # env-set: untouched


def test_refresh_survives_broken_console_db(tmp_path):
    url = make_console_db(tmp_path, [("org-1", "ANTHROPIC_API_KEY", "key")])
    store = ConsoleSecretStore(url, MASTER_KEY)
    env = {**BASE, "ANTHROPIC_API_KEY": ""}
    merged, from_console = apply_console_secrets(env, store)
    cfg = load_config(merged)
    store.engine = sa.create_engine("sqlite:///nonexistent-dir/x.db", future=True)
    store.invalidate()
    refresh_console_secrets(cfg, store, from_console)  # must not raise
    assert cfg.anthropic_api_key.reveal() == "key"
    assert isinstance(cfg.anthropic_api_key, Secret)
